import type { AttackStatus, ServerResponseType } from "./enums.js";
import type { Ship, UpdateRoomData } from "./models.js";

//Player
export interface RegRequest {
  type: "reg";
  data: {
    name: string;
    password: string;
  };
  id: 0;
}

export interface RegResponse {
  type: "reg";
  data: {
    name: string;
    index: number | string;
    error: boolean;
    errorText: string;
  };
  id: 0;
}

export interface WinnersResponse {
  type: "update_winners";
  data: [
    {
      name: string;
      wins: number;
    }
  ];
  id: 0;
}

//Room
export interface CreateRoomRequest {
  type: "create_room";
  data: "";
  id: 0;
}

export interface AddUserToRoomRequest {
  type: "add_user_to_room";
  data: {
    indexRoom: number | string;
  };
  id: 0;
}

export interface CreateGameResponse {
  type: "create_game"; //send for both players in the room, after they are connected to the room
  data: {
    idGame: number | string;
    idPlayer:
      | number
      | string /* generated by server id for player in the game session, not enemy (unique id for every player) */;
  };
  id: 0;
}

export interface UpdateRoomResponse {
  type: "update_room";
  data: UpdateRoomData[];
  id: 0;
}

//Ships
export interface AddShipsRequest {
  type: "add_ships";
  data: {
    gameId: number | string;
    ships: Ship[];
    indexPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
  id: 0;
}

export interface StartGameResponse {
  type: "start_game";
  data: {
    ships: Ship[] /* player's ships, not enemy's */;
    currentPlayerIndex:
      | number
      | string /* id of the player in the current game session, who have sent his ships */;
  };
  id: 0;
}

//Game
export interface AttackRequest {
  type: "attack";
  data: {
    gameId: number | string;
    x: number;
    y: number;
    indexPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
  id: 0;
}

export interface AttackResponse {
  type: "attack";
  data: {
    position: {
      x: number;
      y: number;
    };
    currentPlayer:
      | number
      | string /* id of the player in the current game session */;
    status: AttackStatus;
  };
  id: 0;
}

export interface RandomAttackRequest {
  type: "randomAttack";
  data: {
    gameId: number | string;
    indexPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
  id: 0;
}

export interface TurnResponse {
  type: "turn";
  data: {
    currentPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
  id: 0;
}

export interface FinishResponse {
  type: "finish";
  data: {
    winPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
  id: 0;
}

//message
export type ClientMessage =
  | CreateRoomRequest
  | AddUserToRoomRequest
  | RegRequest
  | AttackRequest
  | RandomAttackRequest
  | AddShipsRequest;

export type ServerMessage =
  | CreateGameResponse
  | UpdateRoomResponse
  | RegResponse
  | WinnersResponse
  | AttackResponse
  | TurnResponse
  | FinishResponse
  | StartGameResponse;

export interface ServerMessageStr {
  type: ServerResponseType;
  data: string;
  id: 0;
}
